<?php
/**
 * CampaignApi
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infusionsoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CollingMedia\Infusionsoft\Api;

use \CollingMedia\Infusionsoft\ApiClient;
use \CollingMedia\Infusionsoft\ApiException;
use \CollingMedia\Infusionsoft\Configuration;
use \CollingMedia\Infusionsoft\ObjectSerializer;

/**
 * CampaignApi Class Doc Comment
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignApi
{
    /**
     * API Client
     *
     * @var \CollingMedia\Infusionsoft\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \CollingMedia\Infusionsoft\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\CollingMedia\Infusionsoft\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \CollingMedia\Infusionsoft\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \CollingMedia\Infusionsoft\ApiClient $apiClient set the API client
     *
     * @return CampaignApi
     */
    public function setApiClient(\CollingMedia\Infusionsoft\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation addContactsToCampaignSequenceUsingPOST
     *
     * Add to Campaign Sequence
     *
     * @param int $campaign_id campaignId (required)
     * @param int $sequence_id sequenceId (required)
     * @param int $contact_id contactId (required)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return void
     */
    public function addContactsToCampaignSequenceUsingPOST($campaign_id, $sequence_id, $contact_id)
    {
        list($response) = $this->addContactsToCampaignSequenceUsingPOSTWithHttpInfo($campaign_id, $sequence_id, $contact_id);
        return $response;
    }

    /**
     * Operation addContactsToCampaignSequenceUsingPOSTWithHttpInfo
     *
     * Add to Campaign Sequence
     *
     * @param int $campaign_id campaignId (required)
     * @param int $sequence_id sequenceId (required)
     * @param int $contact_id contactId (required)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function addContactsToCampaignSequenceUsingPOSTWithHttpInfo($campaign_id, $sequence_id, $contact_id)
    {
        // verify the required parameter 'campaign_id' is set
        if ($campaign_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $campaign_id when calling addContactsToCampaignSequenceUsingPOST');
        }
        // verify the required parameter 'sequence_id' is set
        if ($sequence_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sequence_id when calling addContactsToCampaignSequenceUsingPOST');
        }
        // verify the required parameter 'contact_id' is set
        if ($contact_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $contact_id when calling addContactsToCampaignSequenceUsingPOST');
        }
        // parse inputs
        $resourcePath = "/campaigns/{campaignId}/sequences/{sequenceId}/contacts/{contactId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($campaign_id !== null) {
            $resourcePath = str_replace(
                "{" . "campaignId" . "}",
                $this->apiClient->getSerializer()->toPathValue($campaign_id),
                $resourcePath
            );
        }
        // path params
        if ($sequence_id !== null) {
            $resourcePath = str_replace(
                "{" . "sequenceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($sequence_id),
                $resourcePath
            );
        }
        // path params
        if ($contact_id !== null) {
            $resourcePath = str_replace(
                "{" . "contactId" . "}",
                $this->apiClient->getSerializer()->toPathValue($contact_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/campaigns/{campaignId}/sequences/{sequenceId}/contacts/{contactId}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation addContactsToCampaignSequenceUsingPOST1
     *
     * Add Multiple to Campaign Sequence
     *
     * @param int $campaign_id campaignId (required)
     * @param int $sequence_id sequenceId (required)
     * @param \CollingMedia\Infusionsoft\Model\Ids $ids ids (required)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return void
     */
    public function addContactsToCampaignSequenceUsingPOST1($campaign_id, $sequence_id, $ids)
    {
        list($response) = $this->addContactsToCampaignSequenceUsingPOST1WithHttpInfo($campaign_id, $sequence_id, $ids);
        return $response;
    }

    /**
     * Operation addContactsToCampaignSequenceUsingPOST1WithHttpInfo
     *
     * Add Multiple to Campaign Sequence
     *
     * @param int $campaign_id campaignId (required)
     * @param int $sequence_id sequenceId (required)
     * @param \CollingMedia\Infusionsoft\Model\Ids $ids ids (required)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function addContactsToCampaignSequenceUsingPOST1WithHttpInfo($campaign_id, $sequence_id, $ids)
    {
        // verify the required parameter 'campaign_id' is set
        if ($campaign_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $campaign_id when calling addContactsToCampaignSequenceUsingPOST1');
        }
        // verify the required parameter 'sequence_id' is set
        if ($sequence_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sequence_id when calling addContactsToCampaignSequenceUsingPOST1');
        }
        // verify the required parameter 'ids' is set
        if ($ids === null) {
            throw new \InvalidArgumentException('Missing the required parameter $ids when calling addContactsToCampaignSequenceUsingPOST1');
        }
        // parse inputs
        $resourcePath = "/campaigns/{campaignId}/sequences/{sequenceId}/contacts";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($campaign_id !== null) {
            $resourcePath = str_replace(
                "{" . "campaignId" . "}",
                $this->apiClient->getSerializer()->toPathValue($campaign_id),
                $resourcePath
            );
        }
        // path params
        if ($sequence_id !== null) {
            $resourcePath = str_replace(
                "{" . "sequenceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($sequence_id),
                $resourcePath
            );
        }
        // body params
        $_tempBody = null;
        if (isset($ids)) {
            $_tempBody = $ids;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/campaigns/{campaignId}/sequences/{sequenceId}/contacts'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getAllCampaignsUsingGET
     *
     * List Campaigns
     *
     * @param int $limit Sets a total of items to return (optional)
     * @param int $offset Sets a beginning range of items to return (optional)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return \CollingMedia\Infusionsoft\Model\InlineResponse2002
     */
    public function getAllCampaignsUsingGET($limit = null, $offset = null)
    {
        list($response) = $this->getAllCampaignsUsingGETWithHttpInfo($limit, $offset);
        return $response;
    }

    /**
     * Operation getAllCampaignsUsingGETWithHttpInfo
     *
     * List Campaigns
     *
     * @param int $limit Sets a total of items to return (optional)
     * @param int $offset Sets a beginning range of items to return (optional)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return array of \CollingMedia\Infusionsoft\Model\InlineResponse2002, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllCampaignsUsingGETWithHttpInfo($limit = null, $offset = null)
    {
        // parse inputs
        $resourcePath = "/campaigns";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = $this->apiClient->getSerializer()->toQueryValue($offset);
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\CollingMedia\Infusionsoft\Model\InlineResponse2002',
                '/campaigns'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\CollingMedia\Infusionsoft\Model\InlineResponse2002', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\CollingMedia\Infusionsoft\Model\InlineResponse2002', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getCampaignUsingGET
     *
     * Retrieve a Campaign
     *
     * @param int $campaign_id campaignId (required)
     * @param string[] $optional_properties Comma-delimited list of Campaign properties to include in the response. (The fields &#x60;goals&#x60; and &#x60;sequences&#x60; aren&#39;t included, by default.) (optional)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return \CollingMedia\Infusionsoft\Model\InlineResponse2002Campaigns
     */
    public function getCampaignUsingGET($campaign_id, $optional_properties = null)
    {
        list($response) = $this->getCampaignUsingGETWithHttpInfo($campaign_id, $optional_properties);
        return $response;
    }

    /**
     * Operation getCampaignUsingGETWithHttpInfo
     *
     * Retrieve a Campaign
     *
     * @param int $campaign_id campaignId (required)
     * @param string[] $optional_properties Comma-delimited list of Campaign properties to include in the response. (The fields &#x60;goals&#x60; and &#x60;sequences&#x60; aren&#39;t included, by default.) (optional)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return array of \CollingMedia\Infusionsoft\Model\InlineResponse2002Campaigns, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCampaignUsingGETWithHttpInfo($campaign_id, $optional_properties = null)
    {
        // verify the required parameter 'campaign_id' is set
        if ($campaign_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $campaign_id when calling getCampaignUsingGET');
        }
        // parse inputs
        $resourcePath = "/campaigns/{campaignId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if (is_array($optional_properties)) {
            $optional_properties = $this->apiClient->getSerializer()->serializeCollection($optional_properties, 'multi', true);
        }
        if ($optional_properties !== null) {
            $queryParams['optional_properties'] = $this->apiClient->getSerializer()->toQueryValue($optional_properties);
        }
        // path params
        if ($campaign_id !== null) {
            $resourcePath = str_replace(
                "{" . "campaignId" . "}",
                $this->apiClient->getSerializer()->toPathValue($campaign_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\CollingMedia\Infusionsoft\Model\InlineResponse2002Campaigns',
                '/campaigns/{campaignId}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\CollingMedia\Infusionsoft\Model\InlineResponse2002Campaigns', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\CollingMedia\Infusionsoft\Model\InlineResponse2002Campaigns', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation removeContactsFromCampaignSequenceUsingDELETE
     *
     * Remove from Campaign Sequence
     *
     * @param int $campaign_id campaignId (required)
     * @param int $sequence_id sequenceId (required)
     * @param int $contact_id contactId (required)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return void
     */
    public function removeContactsFromCampaignSequenceUsingDELETE($campaign_id, $sequence_id, $contact_id)
    {
        list($response) = $this->removeContactsFromCampaignSequenceUsingDELETEWithHttpInfo($campaign_id, $sequence_id, $contact_id);
        return $response;
    }

    /**
     * Operation removeContactsFromCampaignSequenceUsingDELETEWithHttpInfo
     *
     * Remove from Campaign Sequence
     *
     * @param int $campaign_id campaignId (required)
     * @param int $sequence_id sequenceId (required)
     * @param int $contact_id contactId (required)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function removeContactsFromCampaignSequenceUsingDELETEWithHttpInfo($campaign_id, $sequence_id, $contact_id)
    {
        // verify the required parameter 'campaign_id' is set
        if ($campaign_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $campaign_id when calling removeContactsFromCampaignSequenceUsingDELETE');
        }
        // verify the required parameter 'sequence_id' is set
        if ($sequence_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sequence_id when calling removeContactsFromCampaignSequenceUsingDELETE');
        }
        // verify the required parameter 'contact_id' is set
        if ($contact_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $contact_id when calling removeContactsFromCampaignSequenceUsingDELETE');
        }
        // parse inputs
        $resourcePath = "/campaigns/{campaignId}/sequences/{sequenceId}/contacts/{contactId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($campaign_id !== null) {
            $resourcePath = str_replace(
                "{" . "campaignId" . "}",
                $this->apiClient->getSerializer()->toPathValue($campaign_id),
                $resourcePath
            );
        }
        // path params
        if ($sequence_id !== null) {
            $resourcePath = str_replace(
                "{" . "sequenceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($sequence_id),
                $resourcePath
            );
        }
        // path params
        if ($contact_id !== null) {
            $resourcePath = str_replace(
                "{" . "contactId" . "}",
                $this->apiClient->getSerializer()->toPathValue($contact_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/campaigns/{campaignId}/sequences/{sequenceId}/contacts/{contactId}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation removeContactsFromCampaignSequenceUsingDELETE1
     *
     * Remove Multiple from Campaign Sequence
     *
     * @param int $campaign_id campaignId (required)
     * @param int $sequence_id sequenceId (required)
     * @param \CollingMedia\Infusionsoft\Model\Ids1 $ids ids (required)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return void
     */
    public function removeContactsFromCampaignSequenceUsingDELETE1($campaign_id, $sequence_id, $ids)
    {
        list($response) = $this->removeContactsFromCampaignSequenceUsingDELETE1WithHttpInfo($campaign_id, $sequence_id, $ids);
        return $response;
    }

    /**
     * Operation removeContactsFromCampaignSequenceUsingDELETE1WithHttpInfo
     *
     * Remove Multiple from Campaign Sequence
     *
     * @param int $campaign_id campaignId (required)
     * @param int $sequence_id sequenceId (required)
     * @param \CollingMedia\Infusionsoft\Model\Ids1 $ids ids (required)
     * @throws \CollingMedia\Infusionsoft\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function removeContactsFromCampaignSequenceUsingDELETE1WithHttpInfo($campaign_id, $sequence_id, $ids)
    {
        // verify the required parameter 'campaign_id' is set
        if ($campaign_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $campaign_id when calling removeContactsFromCampaignSequenceUsingDELETE1');
        }
        // verify the required parameter 'sequence_id' is set
        if ($sequence_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sequence_id when calling removeContactsFromCampaignSequenceUsingDELETE1');
        }
        // verify the required parameter 'ids' is set
        if ($ids === null) {
            throw new \InvalidArgumentException('Missing the required parameter $ids when calling removeContactsFromCampaignSequenceUsingDELETE1');
        }
        // parse inputs
        $resourcePath = "/campaigns/{campaignId}/sequences/{sequenceId}/contacts";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($campaign_id !== null) {
            $resourcePath = str_replace(
                "{" . "campaignId" . "}",
                $this->apiClient->getSerializer()->toPathValue($campaign_id),
                $resourcePath
            );
        }
        // path params
        if ($sequence_id !== null) {
            $resourcePath = str_replace(
                "{" . "sequenceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($sequence_id),
                $resourcePath
            );
        }
        // body params
        $_tempBody = null;
        if (isset($ids)) {
            $_tempBody = $ids;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/campaigns/{campaignId}/sequences/{sequenceId}/contacts'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
