<?php
/**
 * InlineResponse2002SequencesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infusionsoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\Infusionsoft;

/**
 * InlineResponse2002SequencesTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2002Sequences
/**
 * @package     CollingMedia\Infusionsoft
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002SequencesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2002Sequences"
     */
    public function testInlineResponse2002Sequences()
    {
    }

    /**
     * Test attribute "active_contact_count"
     */
    public function testPropertyActiveContactCount()
    {
    }

    /**
     * Test attribute "active_contact_count_completed"
     */
    public function testPropertyActiveContactCountCompleted()
    {
    }

    /**
     * Test attribute "historical_contact_count"
     */
    public function testPropertyHistoricalContactCount()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "paths"
     */
    public function testPropertyPaths()
    {
    }
}
