<?php
/**
 * InlineResponse2002CampaignsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infusionsoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\Infusionsoft;

/**
 * InlineResponse2002CampaignsTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2002Campaigns
/**
 * @package     CollingMedia\Infusionsoft
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002CampaignsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2002Campaigns"
     */
    public function testInlineResponse2002Campaigns()
    {
    }

    /**
     * Test attribute "active_contact_count"
     */
    public function testPropertyActiveContactCount()
    {
    }

    /**
     * Test attribute "completed_contact_count"
     */
    public function testPropertyCompletedContactCount()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
    }

    /**
     * Test attribute "goals"
     */
    public function testPropertyGoals()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "published_date"
     */
    public function testPropertyPublishedDate()
    {
    }

    /**
     * Test attribute "published_status"
     */
    public function testPropertyPublishedStatus()
    {
    }

    /**
     * Test attribute "published_time_zone"
     */
    public function testPropertyPublishedTimeZone()
    {
    }

    /**
     * Test attribute "sequences"
     */
    public function testPropertySequences()
    {
    }

    /**
     * Test attribute "time_zone"
     */
    public function testPropertyTimeZone()
    {
    }
}
