<?php
/**
 * InlineResponse20012ProductOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infusionsoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\Infusionsoft;

/**
 * InlineResponse20012ProductOptionsTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse20012ProductOptions
/**
 * @package     CollingMedia\Infusionsoft
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20012ProductOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20012ProductOptions"
     */
    public function testInlineResponse20012ProductOptions()
    {
    }

    /**
     * Test attribute "allow_spaces"
     */
    public function testPropertyAllowSpaces()
    {
    }

    /**
     * Test attribute "can_contain_character"
     */
    public function testPropertyCanContainCharacter()
    {
    }

    /**
     * Test attribute "can_contain_number"
     */
    public function testPropertyCanContainNumber()
    {
    }

    /**
     * Test attribute "can_end_with_character"
     */
    public function testPropertyCanEndWithCharacter()
    {
    }

    /**
     * Test attribute "can_end_with_number"
     */
    public function testPropertyCanEndWithNumber()
    {
    }

    /**
     * Test attribute "can_start_with_character"
     */
    public function testPropertyCanStartWithCharacter()
    {
    }

    /**
     * Test attribute "can_start_with_number"
     */
    public function testPropertyCanStartWithNumber()
    {
    }

    /**
     * Test attribute "display_index"
     */
    public function testPropertyDisplayIndex()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "max_chars"
     */
    public function testPropertyMaxChars()
    {
    }

    /**
     * Test attribute "min_chars"
     */
    public function testPropertyMinChars()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "required"
     */
    public function testPropertyRequired()
    {
    }

    /**
     * Test attribute "text_message"
     */
    public function testPropertyTextMessage()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {
    }
}
