<?php
/**
 * AppointmentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infusionsoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Infusionsoft;

use \CollingMedia\Infusionsoft\Configuration;
use \CollingMedia\Infusionsoft\ApiClient;
use \CollingMedia\Infusionsoft\ApiException;
use \CollingMedia\Infusionsoft\ObjectSerializer;

/**
 * AppointmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppointmentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appointmentsUsingGET
     *
     * List Appointments.
     *
     */
    public function testAppointmentsUsingGET()
    {
    }

    /**
     * Test case for createAppointmentUsingPOST
     *
     * Create an Appointment.
     *
     */
    public function testCreateAppointmentUsingPOST()
    {
    }

    /**
     * Test case for loadAppointmentUsingGET
     *
     * Retrieve an Appointment.
     *
     */
    public function testLoadAppointmentUsingGET()
    {
    }

    /**
     * Test case for removeAppointmentUsingDELETE
     *
     * Delete an Appointment.
     *
     */
    public function testRemoveAppointmentUsingDELETE()
    {
    }

    /**
     * Test case for replaceAppointmentUsingPUT
     *
     * Replace an Appointment.
     *
     */
    public function testReplaceAppointmentUsingPUT()
    {
    }

    /**
     * Test case for searchUsingGET
     *
     * Search Appointments.
     *
     */
    public function testSearchUsingGET()
    {
    }

    /**
     * Test case for syncUsingGET
     *
     * Retrieve Synced Appointments.
     *
     */
    public function testSyncUsingGET()
    {
    }

    /**
     * Test case for updateAppointmentUsingPATCH
     *
     * Update an Appointment.
     *
     */
    public function testUpdateAppointmentUsingPATCH()
    {
    }
}
