<?php
/**
 * CampaignApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infusionsoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Infusionsoft;

use \CollingMedia\Infusionsoft\Configuration;
use \CollingMedia\Infusionsoft\ApiClient;
use \CollingMedia\Infusionsoft\ApiException;
use \CollingMedia\Infusionsoft\ObjectSerializer;

/**
 * CampaignApiTest Class Doc Comment
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addContactsToCampaignSequenceUsingPOST
     *
     * Add to Campaign Sequence.
     *
     */
    public function testAddContactsToCampaignSequenceUsingPOST()
    {
    }

    /**
     * Test case for addContactsToCampaignSequenceUsingPOST1
     *
     * Add Multiple to Campaign Sequence.
     *
     */
    public function testAddContactsToCampaignSequenceUsingPOST1()
    {
    }

    /**
     * Test case for getAllCampaignsUsingGET
     *
     * List Campaigns.
     *
     */
    public function testGetAllCampaignsUsingGET()
    {
    }

    /**
     * Test case for getCampaignUsingGET
     *
     * Retrieve a Campaign.
     *
     */
    public function testGetCampaignUsingGET()
    {
    }

    /**
     * Test case for removeContactsFromCampaignSequenceUsingDELETE
     *
     * Remove from Campaign Sequence.
     *
     */
    public function testRemoveContactsFromCampaignSequenceUsingDELETE()
    {
    }

    /**
     * Test case for removeContactsFromCampaignSequenceUsingDELETE1
     *
     * Remove Multiple from Campaign Sequence.
     *
     */
    public function testRemoveContactsFromCampaignSequenceUsingDELETE1()
    {
    }
}
