<?php
/**
 * ContactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infusionsoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Infusionsoft;

use \CollingMedia\Infusionsoft\Configuration;
use \CollingMedia\Infusionsoft\ApiClient;
use \CollingMedia\Infusionsoft\ApiException;
use \CollingMedia\Infusionsoft\ObjectSerializer;

/**
 * ContactApiTest Class Doc Comment
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for applyTagsToContactIdUsingPOST
     *
     * Apply Tags.
     *
     */
    public function testApplyTagsToContactIdUsingPOST()
    {
    }

    /**
     * Test case for createContactUsingPOST
     *
     * Create a Contact.
     *
     */
    public function testCreateContactUsingPOST()
    {
    }

    /**
     * Test case for createOrUpdateContactUsingPUT
     *
     * Create or Update a Contact.
     *
     */
    public function testCreateOrUpdateContactUsingPUT()
    {
    }

    /**
     * Test case for deleteContactUsingDELETE
     *
     * Delete a Contact.
     *
     */
    public function testDeleteContactUsingDELETE()
    {
    }

    /**
     * Test case for listAppliedTagsUsingGET
     *
     * List Applied Tags.
     *
     */
    public function testListAppliedTagsUsingGET()
    {
    }

    /**
     * Test case for listContactsUsingGET
     *
     * List Contacts.
     *
     */
    public function testListContactsUsingGET()
    {
    }

    /**
     * Test case for listCustomFieldsUsingGET
     *
     * List Contact Custom Fields.
     *
     */
    public function testListCustomFieldsUsingGET()
    {
    }

    /**
     * Test case for loadUsingGET
     *
     * Retrieve a Contact.
     *
     */
    public function testLoadUsingGET()
    {
    }

    /**
     * Test case for removeTagsFromContactUsingDELETE
     *
     * Remove Applied Tag.
     *
     */
    public function testRemoveTagsFromContactUsingDELETE()
    {
    }

    /**
     * Test case for removeTagsFromContactUsingDELETE1
     *
     * Remove Applied Tags.
     *
     */
    public function testRemoveTagsFromContactUsingDELETE1()
    {
    }

    /**
     * Test case for updateContactUsingPATCH
     *
     * Update a Contact.
     *
     */
    public function testUpdateContactUsingPATCH()
    {
    }
}
