<?php
/**
 * ECommerceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infusionsoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Infusionsoft;

use \CollingMedia\Infusionsoft\Configuration;
use \CollingMedia\Infusionsoft\ApiClient;
use \CollingMedia\Infusionsoft\ApiException;
use \CollingMedia\Infusionsoft\ObjectSerializer;

/**
 * ECommerceApiTest Class Doc Comment
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ECommerceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for loadOrderUsingGET
     *
     * Retrieve an Order.
     *
     */
    public function testLoadOrderUsingGET()
    {
    }

    /**
     * Test case for searchUsingGET1
     *
     * List Orders.
     *
     */
    public function testSearchUsingGET1()
    {
    }

    /**
     * Test case for searchUsingGET2
     *
     * List Transactions.
     *
     */
    public function testSearchUsingGET2()
    {
    }

    /**
     * Test case for transactionByIdUsingGET
     *
     * Retrieve a Transaction.
     *
     */
    public function testTransactionByIdUsingGET()
    {
    }

    /**
     * Test case for transactionsForOrderUsingGET
     *
     * Retrieve Order Transactions.
     *
     */
    public function testTransactionsForOrderUsingGET()
    {
    }
}
