<?php
/**
 * OpportunityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infusionsoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Infusionsoft;

use \CollingMedia\Infusionsoft\Configuration;
use \CollingMedia\Infusionsoft\ApiClient;
use \CollingMedia\Infusionsoft\ApiException;
use \CollingMedia\Infusionsoft\ObjectSerializer;

/**
 * OpportunityApiTest Class Doc Comment
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OpportunityApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOpportunityUsingPOST
     *
     * Create an Opportunity.
     *
     */
    public function testCreateOpportunityUsingPOST()
    {
    }

    /**
     * Test case for getOpportunityUsingGET
     *
     * Retrieve an Opportunity.
     *
     */
    public function testGetOpportunityUsingGET()
    {
    }

    /**
     * Test case for getStagePipelineUsingGET
     *
     * List Opportunity Stage Pipeline.
     *
     */
    public function testGetStagePipelineUsingGET()
    {
    }

    /**
     * Test case for listOpportunitiesUsingGET
     *
     * List Opportunities.
     *
     */
    public function testListOpportunitiesUsingGET()
    {
    }

    /**
     * Test case for replaceOpportunityUsingPUT
     *
     * Replace an Opportunity.
     *
     */
    public function testReplaceOpportunityUsingPUT()
    {
    }

    /**
     * Test case for updateOpportunityUsingPATCH
     *
     * Update an Opportunity.
     *
     */
    public function testUpdateOpportunityUsingPATCH()
    {
    }
}
