<?php
/**
 * TagsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infusionsoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Infusionsoft;

use \CollingMedia\Infusionsoft\Configuration;
use \CollingMedia\Infusionsoft\ApiClient;
use \CollingMedia\Infusionsoft\ApiException;
use \CollingMedia\Infusionsoft\ObjectSerializer;

/**
 * TagsApiTest Class Doc Comment
 *
 * @category Class
 * @package  CollingMedia\Infusionsoft
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TagsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for applyTagToContactIdsUsingPOST
     *
     * Apply Tag to Contacts.
     *
     */
    public function testApplyTagToContactIdsUsingPOST()
    {
    }

    /**
     * Test case for listContactsForTagIdUsingGET
     *
     * List Tagged Contacts.
     *
     */
    public function testListContactsForTagIdUsingGET()
    {
    }

    /**
     * Test case for removeTagFromContactIdUsingDELETE
     *
     * Remove Tag from Contact.
     *
     */
    public function testRemoveTagFromContactIdUsingDELETE()
    {
    }

    /**
     * Test case for removeTagFromContactIdsUsingDELETE
     *
     * Remove Tag from Contacts.
     *
     */
    public function testRemoveTagFromContactIdsUsingDELETE()
    {
    }
}
